name: NIGHTLORD
favicon: null
layout_spectrum: 0.64995
typography_spectrum: 0.40686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22a0e0'
    - '#000000'
    - '#d0d0d0'
    - '#7e7e7e'
    - '#104d6c'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
